spring:
  config:
    activate:
      on-profile: local
  datasource:
    postgresql:
      hikari:
        data-source-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: admin1!
        connection-test-query: SELECT 1
      mariadb:
        hikari:
          data-source-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://localhost:3306/study_db
          username: root
          password: admin1!
          connection-test-query: SELECT 1

server:
  port: 8080
