server:
  port: 8080

---

spring:
  config:
    activate.on-profile: local

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://oneplat.asuscomm.com:3306/pkqss_mgmt_db?serverTimezone=Asia/Seoul
      username: admin
      password: dbfrhrfh1rk!
      connection-test-query: SELECT 1
    postgresql:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: admin1!
      connection-test-query: SELECT 1
    mariadb:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/test_db
      username: root
      password: admin1!
      connection-test-query: SELECT 1

  jta:
    enabled: true
    atomikos:
      properties:
        log-base-name: tmlog
      datasource:
        mysql:
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            url: ${spring.datasource.mysql.jdbc-url}
            user: ${spring.datasource.mysql.username}
            password: ${spring.datasource.mysql.password}
        postgresql:
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            url: ${spring.datasource.postgresql.jdbc-url}
            user: ${spring.datasource.postgresql.username}
            password: ${spring.datasource.postgresql.password}
        mariadb:
          xa-data-source-class-name: org.mariadb.jdbc.MariaDbDataSource
          xa-properties:
            url: ${spring.datasource.mariadb.jdbc-url}
            user: ${spring.datasource.mariadb.username}
            password: ${spring.datasource.mariadb.password}
